2024-Oct-07 03:49:01.440000 M SEVERE <-mcp(kubernetes.docker.internal:10192) Failed to send TCP bytes -- retrying : java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
2024-Oct-07 03:49:03.780000 M SEVERE <-mcp(kubernetes.docker.internal:10192) Failed to reconnect: java.util.concurrent.ExecutionException: java.io.IOException: The remote computer refused the network connection.

2024-Oct-07 03:49:03.810000 M SEVERE <-mcp(kubernetes.docker.internal:10192) Failed to send TCP bytes -- retrying : java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Oct-07 03:49:05.120000 M SEVERE <-mcp(kubernetes.docker.internal:10192) Failed to reconnect: java.util.concurrent.ExecutionException: java.io.IOException: The remote computer refused the network connection.

2024-Oct-07 03:49:05.242000 M SEVERE <-mcp(kubernetes.docker.internal:10192) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
