2024-Nov-28 12:21:02.325000 M SEVERE     <-obs(kubernetes.docker.internal:10462) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
2024-Nov-28 12:21:02.357000 M SEVERE     <-obs(kubernetes.docker.internal:10462) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-28 12:21:02.411000 M SEVERE <-mcp(kubernetes.docker.internal:10906) Failed to send TCP bytes -- retrying : java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
2024-Nov-28 12:21:04.456000 M SEVERE <-mcp(kubernetes.docker.internal:10906) Failed to reconnect: java.util.concurrent.ExecutionException: java.io.IOException: The remote computer refused the network connection.

2024-Nov-28 12:21:04.457000 M SEVERE <-mcp(kubernetes.docker.internal:10906) Failed to send TCP bytes -- retrying : java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-28 12:21:06.496000 M SEVERE <-mcp(kubernetes.docker.internal:10906) Failed to reconnect: java.util.concurrent.ExecutionException: java.io.IOException: The remote computer refused the network connection.

2024-Nov-28 12:21:06.551000 M SEVERE <-mcp(kubernetes.docker.internal:10906) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-28 12:32:59.197000 M SEVERE     <-obs(kubernetes.docker.internal:10451) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
2024-Nov-28 12:32:59.248000 M SEVERE     <-obs(kubernetes.docker.internal:10451) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-28 12:32:59.300000 M SEVERE     <-obs(kubernetes.docker.internal:10451) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-28 12:32:59.353000 M SEVERE     <-obs(kubernetes.docker.internal:10451) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-28 12:32:59.424000 M SEVERE <-mcp(kubernetes.docker.internal:10236) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
