2024-Nov-07 05:00:42.806000 M SEVERE     <-mcp(kubernetes.docker.internal:10843) Failed to connectWithTimeout AsynchronousSocketChannel: java.util.concurrent.ExecutionException: java.io.IOException: The remote computer refused the network connection.

2024-Nov-07 05:00:42.896000 M SEVERE <-mcp(kubernetes.docker.internal:10843) Failed to send TCP bytes -- retrying : java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-07 05:00:44.952000 M SEVERE <-mcp(kubernetes.docker.internal:10843) Failed to reconnect: java.util.concurrent.ExecutionException: java.io.IOException: The remote computer refused the network connection.

