2024-Sep-23 13:21:31.894000 M SEVERE <-mcp(kubernetes.docker.internal:10475) Failed to send TCP bytes -- retrying : java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
2024-Sep-23 13:21:33.940000 M SEVERE <-mcp(kubernetes.docker.internal:10475) Failed to reconnect: java.util.concurrent.ExecutionException: java.io.IOException: The remote computer refused the network connection.

2024-Sep-23 13:22:27.914000 M SEVERE     <-obs(kubernetes.docker.internal:10321) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
2024-Sep-23 13:22:28.150000 M SEVERE     <-obs(kubernetes.docker.internal:10321) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Sep-23 13:22:28.160000 M SEVERE     <-obs(kubernetes.docker.internal:10321) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Sep-23 13:22:28.520000 M SEVERE     <-obs(kubernetes.docker.internal:10321) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Sep-23 13:22:28.131000 M SEVERE <-mcp(kubernetes.docker.internal:10350) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
