2024-Nov-23 05:41:24.511000 M SEVERE     <-obs(kubernetes.docker.internal:10124) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
2024-Nov-23 05:41:24.566000 M SEVERE     <-obs(kubernetes.docker.internal:10124) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-23 05:41:24.624000 M SEVERE     <-obs(kubernetes.docker.internal:10124) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-23 05:41:24.674000 M SEVERE     <-obs(kubernetes.docker.internal:10124) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-23 05:41:24.795000 M SEVERE <-mcp(kubernetes.docker.internal:10021) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
2024-Nov-23 06:22:06.741000 M SEVERE     <-obs(kubernetes.docker.internal:10024) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
2024-Nov-23 06:22:06.743000 M SEVERE     <-obs(kubernetes.docker.internal:10024) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-23 06:22:06.799000 M SEVERE     <-obs(kubernetes.docker.internal:10024) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-23 06:22:06.857000 M SEVERE     <-obs(kubernetes.docker.internal:10024) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-23 06:22:06.970000 M SEVERE <-mcp(kubernetes.docker.internal:10738) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
2024-Nov-23 06:31:12.177000 M SEVERE     <-obs(kubernetes.docker.internal:10830) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
2024-Nov-23 06:31:12.234000 M SEVERE     <-obs(kubernetes.docker.internal:10830) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-23 06:31:12.283000 M SEVERE <-mcp(kubernetes.docker.internal:10486) Failed to send TCP bytes -- retrying : java.util.concurrent.ExecutionException: java.io.IOException: An existing connection was forcibly closed by the remote host
2024-Nov-23 06:31:14.317000 M SEVERE <-mcp(kubernetes.docker.internal:10486) Failed to reconnect: java.util.concurrent.ExecutionException: java.io.IOException: The remote computer refused the network connection.

2024-Nov-23 06:31:14.318000 M SEVERE <-mcp(kubernetes.docker.internal:10486) Failed to send TCP bytes -- retrying : java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
2024-Nov-23 06:31:16.369000 M SEVERE <-mcp(kubernetes.docker.internal:10486) Failed to reconnect: java.util.concurrent.ExecutionException: java.io.IOException: The remote computer refused the network connection.

2024-Nov-23 06:31:16.427000 M SEVERE <-mcp(kubernetes.docker.internal:10486) Failed to send TCP bytes: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
